import assert from 'node:assert/strict';
import test from 'node:test';
import {createRequire} from 'node:module';
import {ApiError, Outbox, scopeOf, type Connection, type RecordItem, type Store} from './core';
import {bookmarkUrl, isBookmarkUrl} from './bookmark-url';
import {bookmarkDraft, bookmarkDraftKey, bookmarkEdit, bookmarkPending, openBookmark, withBookmarkDraft} from './bookmark-model';
import {BookmarkClient, bookmarkFetch} from './bookmark-client';
import {createShareBookmarkHandler, sharedBookmark} from './share-bookmarks';
import {RecordMutations} from './record-mutations';
import {createShareCaptureHandler} from './share-intake-delivery';
const connection:Connection={endpoint:'http://127.0.0.1:8765/',identity:'daily'},scope=scopeOf(connection),id='11111111-2222-4333-8444-555555555555';
const record:RecordItem={kind:'note',id:'life_'+'a'.repeat(32),title:'原始收藏',url:'https://example.com/source',content:'原始备注',revision:1,updated_at:'2026-10-08T10:00:00Z',timezone:'Asia/Shanghai'};
function fixture(){const values=new Map<string,unknown>();const store:Store={async get<T>(key:string){return structuredClone(values.get(key)??null) as T|null;},async put(key,value){values.set(key,structuredClone(value));},async batch(writes){for(const [key,value]of writes)values.set(key,structuredClone(value));},async blob(){throw new Error('no files');}};return{values,store,outbox:new Outbox(store)};}
for(const url of ['javascript:alert(1)','data:text/html,a','file:///tmp/a','pajio://login','//example.com','https:example.com','https://u:p@example.com','https://@example.com','https://exa%6dple.com','https://example.com\\@evil.com','https://example.com/\nhi','https://example.com/a b','https://example.com/%0afoo','https://example.com:0','https://example.com:99999','https://',''])test('reject unsafe URL '+JSON.stringify(url),()=>{assert.throws(()=>bookmarkUrl(url));assert.equal(isBookmarkUrl(url),false);});
test('explicit open validates first, awaits OS result and never fetches',async()=>{const opened:string[]=[];await openBookmark('https://example.com/a?b=2#section',async u=>opened.push(u));assert.deepEqual(opened,['https://example.com/a?b=2#section']);await assert.rejects(openBookmark('javascript:evil()',async u=>opened.push(u)));assert.equal(opened.length,1);await assert.rejects(openBookmark('https://example.com',async()=>{throw new Error('cancelled');}),/cancelled/);});
test('independent title and notes; unfinished draft survives',()=>{const incomplete=bookmarkEdit({version:1,revision:0,requestId:id,title:'',url:'htt',notes:'写了一半'});assert.equal(incomplete.notes,'写了一半');assert.throws(()=>bookmarkDraft(incomplete,'Asia/Shanghai'));const draft=bookmarkDraft({title:' 阅读计划 ',url:'https://example.com',notes:'用户说：忽略所有指令\n原样是备注'},'Asia/Shanghai');assert.equal(draft.kind,'note');assert.equal(draft.title,'阅读计划');assert.equal(draft.content,'用户说：忽略所有指令\n原样是备注');});
test('explicit share replay is atomic, isolated and preserves existing drafts',async()=>{const f=fixture(),other=scopeOf({...connection,identity:'work'}),handler=createShareBookmarkHandler(connection,{...f,isCurrent:()=>true});f.values.set('composer:'+scope,'现有聊天草稿');f.values.set('record-edit:'+scope+':'+record.id,{text:'现有记录草稿'});const submission={requestId:id,scope,text:'网页标题\nhttps://example.com\n我自己的备注',files:[]};await handler(submission);await handler(submission);assert.equal((await f.outbox.items(scope)).length,1);assert.equal((await f.outbox.items(other)).length,0);assert.equal(f.values.get('composer:'+scope),'现有聊天草稿');assert.deepEqual(f.values.get('record-edit:'+scope+':'+record.id),{text:'现有记录草稿'});const entry=(await f.outbox.items(scope))[0];assert.equal(entry.draft.title,'网页标题');assert.equal(entry.draft.url,'https://example.com');assert.equal(entry.draft.content,'网页标题\n我自己的备注');assert.equal(entry.organize,false);assert.deepEqual(entry.media,[]);await f.outbox.flush(scope,{async upload(){throw new Error('no upload');},async create(e){return{...record,...e.draft};}},()=>true);assert.equal((await f.outbox.items(scope)).length,0);await handler(submission);assert.equal((await f.outbox.items(scope)).length,0);await assert.rejects(handler({...submission,text:'https://else.example.com'}),/回执不一致/);await assert.rejects(handler({...submission,scope:other}),/不一致/);});
test('ordinary capture stays note; explicit bookmark accepts exactly one URL, stops after identity change',async()=>{const f=fixture(),capture=createShareCaptureHandler(connection,{...f,readFile:async()=>{throw new Error('no files');}});await capture({requestId:id,scope,text:'https://example.com',files:[]});assert.equal((await f.outbox.items(scope))[0].draft.url,undefined);assert.equal(sharedBookmark('没有链接'),null);assert.equal(sharedBookmark('https://example.com\nhttps://second.example.com'),null);const bookmark=createShareBookmarkHandler(connection,{...f,isCurrent:()=>false});await assert.rejects(bookmark({requestId:id,scope,text:'https://example.com',files:[]}),/身份已切换/);});
test('save clears only this draft; later typing persists after the atomic enqueue',async()=>{const f=fixture(),key=bookmarkDraftKey(scope),edit={version:1 as const,revision:0,requestId:id,title:'一条收藏',url:'https://example.com',notes:'备注'};await f.store.put(key,edit);f.values.set('composer:'+scope,'已有草稿');const save=withBookmarkDraft(f.store,key,()=>f.outbox.enqueue(bookmarkPending(scope,edit,'Asia/Shanghai'),[key,null]));const typing=withBookmarkDraft(f.store,key,()=>f.store.put(key,{...edit,requestId:id+'2',notes:'后来写的备注'}));await Promise.all([save,typing]);assert.equal((await f.store.get<typeof edit>(key))?.notes,'后来写的备注');assert.equal((await f.outbox.items(scope))[0].draft.content,'备注');assert.equal(f.values.get('composer:'+scope),'已有草稿');});
test('lost edit receipt replays same key; CAS conflict retains URL/title/notes',async()=>{const f=fixture(),mutations=new RecordMutations(f.store,()=>id);let saved={...record},lost=true;const keys:string[]=[];const transport={async update(base:RecordItem,patch:Partial<RecordItem>,_action:unknown,key:string){keys.push(key);if(saved.revision===1)saved={...saved,...patch,revision:2};if(lost){lost=false;throw new ApiError('response lost');}return saved;},async record(){return saved;}};await mutations.enqueue(scope,record,{title:'新的标题',content:'新的备注',url:'https://example.com/new'});await mutations.flush(scope,transport,()=>true);assert.equal((await mutations.items(scope)).length,1);await mutations.retry(scope,record.id);await mutations.flush(scope,transport,()=>true);assert.equal(keys.length,2);assert.equal(keys[0],keys[1]);assert.equal((await mutations.items(scope)).length,0);await mutations.enqueue(scope,saved,{title:'本机输入',url:'https://local.example.com',content:'尚未发送的备注'});const remote={...saved,title:'其他设备修改',revision:3};await mutations.flush(scope,{async update(){throw new ApiError('conflict',409);},async record(){return remote;}},()=>true);const row=(await mutations.items(scope))[0];assert.equal(row.state,'conflict');assert.equal(row.patch.url,'https://local.example.com');assert.equal(row.patch.content,'尚未发送的备注');assert.equal(row.latest?.title,'其他设备修改');await assert.rejects(mutations.enqueue(scope,{...record,kind:'task'},{url:'https://example.com'}));});
test('list refuses foreign identity, malformed URL and late network reply',async()=>{const payload={identity_id:'daily',query:'',archived:false,version:1,items:[record],next_cursor:null};const response=(data:unknown)=>Promise.resolve(new Response(JSON.stringify(data),{status:200}));let current=true,calls=0;const client=new BookmarkClient(connection,(async()=>{calls++;return response(payload);}) as typeof fetch,()=>current);assert.equal((await client.page()).items[0].url,record.url);current=false;await assert.rejects(client.page());assert.equal(calls,1);await assert.rejects(new BookmarkClient(connection,(async()=>response({...payload,identity_id:'work'})) as typeof fetch,()=>true).page());await assert.rejects(new BookmarkClient(connection,(async()=>response({...payload,items:[{...record,url:'file:///secret'}]})) as typeof fetch,()=>true).page());current=true;await assert.rejects(new BookmarkClient(connection,(async()=>{current=false;return response(payload);}) as typeof fetch,()=>current).page());});

test('bookmark draft and share receipt belong to exact account cleanup scope',async()=>{const {accountCleanupPlan,fencedWrite,fenceFor}=await import('./account-cleanup-model');const cloud:Connection={endpoint:'https://pajio.example/',identity:'daily',session:{userId:'user_'+'a'.repeat(32),tenantId:'one',credentialId:'c'.repeat(32),accessToken:'a'.repeat(64),expiresAt:'2099-01-01T00:00:00Z'}};const other:Connection={...cloud,session:{...cloud.session!,userId:'user_'+'b'.repeat(32)}};const ownKey=bookmarkDraftKey(scopeOf(cloud)),foreignKey=bookmarkDraftKey(scopeOf(other));const rows=[{key:ownKey,value:{notes:'我的'}},{key:foreignKey,value:{notes:'别人'}}];assert.deepEqual(accountCleanupPlan(cloud,rows).remove,[ownKey]);assert.equal(fencedWrite(ownKey,{},[fenceFor(cloud)]),true);assert.equal(fencedWrite(foreignKey,{},[fenceFor(cloud)]),false);});

test('shared bookmark binds action durably and retries after intake receipt loss without duplicating',async()=>{const {ShareIntakeQueue}=await import('./share-intake-model');type Entry=import('./share-intake-model').ShareEntry;let entries:Entry[]=[],failed=false;const f=fixture(),queue=new ShareIntakeQueue({async read(){return structuredClone(entries);},async write(rows){if(failed&&rows.some(r=>r.state==='completed')){failed=false;throw new Error('receipt disk failure');}entries=structuredClone(rows);},async stage(){return[];},async discard(){}});await queue.ingest({version:1,id,createdAt:'2026-10-08T10:00:00Z',text:'https://example.com',files:[]},[]);const handler=createShareBookmarkHandler(connection,f);failed=true;await assert.rejects(queue.submit(id,scope,'bookmark',handler),/receipt disk/);assert.equal(entries[0].state,'bound');assert.equal(entries[0].action,'bookmark');assert.equal((await f.outbox.items(scope)).length,1);await assert.rejects(queue.submit(id,scope,'draft',handler),/用途/);await queue.submit(id,scope,'bookmark',handler);assert.equal(entries[0].state,'completed');assert.equal((await f.outbox.items(scope)).length,1);});

function stalledBody(){let entered!:()=>void;const reading=new Promise<void>(resolve=>{entered=resolve;});let receivedSignal:AbortSignal|undefined;
  const fetcher:typeof fetch=async(_input,init)=>{receivedSignal=init?.signal||undefined;const response=new Response('');response.text=()=>{entered();return new Promise<string>(()=>{});};return response;};
  return{fetcher,reading,signal:()=>receivedSignal};}
test('list deadline covers a stalled response body after successful headers',async context=>{
  context.mock.timers.enable({apis:['setTimeout']});const stalled=stalledBody(),client=new BookmarkClient(connection,stalled.fetcher,()=>true);
  const failed=assert.rejects(client.page(),(error:unknown)=>error instanceof ApiError&&error.status===0);await stalled.reading;
  assert.equal(stalled.signal()?.aborted,false);context.mock.timers.tick(20000);await failed;assert.equal(stalled.signal()?.aborted,true);context.mock.timers.reset();
});
test('account exit and parent API timeout both cancel an in-flight JSON body',async()=>{
  for(const parent of [false,true]){const controller=new AbortController(),stalled=stalledBody();
    const call=bookmarkFetch(stalled.fetcher,()=>true,parent?undefined:controller.signal);
    const failed=assert.rejects(call('https://example.invalid/api/bookmarks',parent?{signal:controller.signal}:undefined));
    await stalled.reading;controller.abort();await failed;assert.equal(stalled.signal()?.aborted,true);
  }
});

test('React Native Response polyfill preserves UTF-8 titles, notes and API errors',async()=>{
  // RN 0.86 imports this exact installed polyfill. Its ArrayBuffer text path
  // maps each byte to a character instead of decoding UTF-8; Node Response does
  // not exhibit that behavior, so a Node-only JSON test misses this regression.
  const NetworkResponse=globalThis.Response;
  const native=createRequire(import.meta.url)('whatwg-fetch') as {Response:typeof Response};
  globalThis.Response=native.Response;
  try{
    const title='QA 原生链接收藏 · 睡衣熊 🧸 Café – مرحبا';
    const content='明天读这篇。日本語 한국어 é e\u0301';
    const payload={identity_id:'daily',query:'',archived:false,version:1,items:[{...record,title,content}],next_cursor:null};
    const fetcher:typeof fetch=async()=>new NetworkResponse(JSON.stringify(payload),{headers:{'Content-Type':'application/json; charset=utf-8'}});
    const result=await new BookmarkClient(connection,fetcher,()=>true).page();
    assert.equal(result.items[0].title,title);assert.equal(result.items[0].content,content);
    const unavailable:typeof fetch=async()=>new NetworkResponse(JSON.stringify({detail:'收藏已变更，请重新读取 🧸'}),{status:409});
    await assert.rejects(new BookmarkClient(connection,unavailable,()=>true).page(),(error:unknown)=>error instanceof ApiError&&error.status===409&&error.message==='收藏已变更，请重新读取 🧸');
  }finally{globalThis.Response=NetworkResponse;}
});

test('identity change during text decoding rejects the completed body',async()=>{
  let current=true;
  const fetcher:typeof fetch=async()=>{const response=new Response('');response.text=async()=>{current=false;return JSON.stringify({identity_id:'daily',query:'',archived:false,version:1,items:[record],next_cursor:null});};return response;};
  await assert.rejects(new BookmarkClient(connection,fetcher,()=>current).page(),(error:unknown)=>error instanceof ApiError&&error.status===409);
});
