import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {test} from 'node:test';
import {HealthExportRequest,HealthHistoryApi,healthExport,healthHistory} from './health-history';
import {Connection,Store} from './core';
const at='2026-10-08T00:00:00.000Z',id='a'.repeat(32),hash=(bytes:Uint8Array)=>Promise.resolve(createHash('sha256').update(bytes).digest('hex'));
const connection:Connection={endpoint:'https://pajio.example/',identity:'daily',session:{userId:'user_'+'b'.repeat(32),tenantId:'tenant',credentialId:'c'.repeat(32),accessToken:'d'.repeat(64),expiresAt:'2099-01-01T00:00:00Z'}};
function history(){return {schema:1,scope:'current_identity',read_at:at,sampler_running:true,coverage:{retention_seconds:604800,sample_interval_seconds:300,latest_observed_at:at,earliest_retained_at:at,seconds_since_observation:0,freshness:'recent',continuous_uptime_proven:false,mode:'point_in_time_samples'},samples:[{id:1,observed_at:at,source:'manual',deployment:'synthetic',observations:[{component:'engine',status:'fault',code:'engine_timeout',task_id:null,run_id:null,attempt:null,phase:null,last_state_event_at:null}]}],events:[{id:1,sample_id:1,observed_at:at,kind:'condition_started',component:'engine',task_id:null,status:'fault',code:'engine_timeout',previous_status:null,previous_code:null,condition_started_at:at}],samples_truncated:false,events_truncated:false,next_before_sample:null,next_before_event:null};}
const json=(v:unknown,status=200)=>new Response(JSON.stringify(v),{status,headers:{'Content-Type':'application/json'}});
function exported(){const body={schema:1,report_id:id,category:'voice',created_at:at,expires_at:'2026-10-09T00:00:00.000Z',transmission:'not_sent',contents:history()};const bytes=new TextEncoder().encode(JSON.stringify(body));return {body,bytes,metadata:{schema:1,id,category:'voice',created_at:at,expires_at:body.expires_at,transmission:'not_sent',filename:`pajio-diagnostics-${id}.json`,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')}};}
const store=()=>{const data=new Map<string,unknown>();return {get:async<T>(key:string)=>structuredClone(data.get(key)??null) as T|null,put:async(key:string,value:unknown)=>{data.set(key,structuredClone(value));}} as Pick<Store,'get'|'put'>;};
test('closed projection strips unknown private details and rejects invented health or duplicate events',()=>{const v=history();Object.assign(v,{logs:'secret'});Object.assign(v.samples[0].observations[0],{address:'private',body:'private',owner_scope:'private'});const safe=JSON.stringify(healthHistory(v));assert(!safe.includes('secret'));assert(!safe.includes('private'));assert.throws(()=>healthHistory({...v,events:[...v.events,...v.events]}));assert.throws(()=>healthHistory({...v,coverage:{...v.coverage,continuous_uptime_proven:true}}));assert.throws(()=>healthHistory({...v,samples:[{...v.samples[0],observations:[{...v.samples[0].observations[0],status:'all_good'}]}]}));});
test('export metadata rejects category, filename and transmission mismatch',()=>{const {metadata}=exported();assert.equal(healthExport(metadata,'voice').id,id);for(const patch of [{category:'files'},{filename:'../private.json'},{transmission:'sent'},{sha256:'short'}])assert.throws(()=>healthExport({...metadata,...patch},'voice'));});
test('a dropped export response reuses the persisted scoped request and original category after restart',async()=>{const {metadata}=exported(),bodies:unknown[]=[],headers:Headers[]=[];let drop=true;const fetcher=async(input:RequestInfo|URL,init?:RequestInit)=>{headers.push(new Headers(init?.headers));if(String(input).endsWith('/api/bootstrap'))return json({token:'csrf',identities:[{id:'daily'}]});bodies.push(JSON.parse(String(init?.body)));if(drop){drop=false;throw Error('private server detail');}return json(metadata,201);};const storage=store();const first=new HealthExportRequest(storage,new HealthHistoryApi(connection,hash,fetcher));await assert.rejects(first.run('stable-request-key-123','voice'),/尚未确认/);const restored=new HealthExportRequest(storage,new HealthHistoryApi(connection,hash,fetcher));const result=await restored.run('different-request-key','files');assert.equal(result.id,id);assert.deepEqual(bodies,[{request_key:'stable-request-key-123',category:'voice'},{request_key:'stable-request-key-123',category:'voice'}]);assert.equal(headers.at(-1)?.get('X-Wearing-Token'),'csrf');assert.equal(headers.at(-1)?.get('X-Pajio-Expected-Tenant'),'tenant');const other=new HealthExportRequest(storage,new HealthHistoryApi({...connection,session:{...connection.session!,userId:'user_'+'e'.repeat(32)}},hash,fetcher));assert.equal(await other.pending(),null);});
test('403 refresh preserves the mutation key and verifies selected identity',async()=>{const bodies:unknown[]=[];let boots=0;const api=new HealthHistoryApi(connection,hash,async(input,init)=>{if(String(input).endsWith('/api/bootstrap')){boots++;return json({token:'csrf'+boots,identities:[{id:'daily'}]});}bodies.push(JSON.parse(String(init?.body)));return bodies.length===1?json({},403):json(exported().metadata,201);});await api.create('same-request-123456','voice');assert.equal(boots,2);assert.deepEqual(bodies[0],bodies[1]);const wrong=new HealthHistoryApi(connection,hash,async()=>json({token:'csrf',identities:[{id:'work'}]}));await assert.rejects(wrong.create('same-request-123456','voice'),/无法核对/);});
test('download verifies byte count, digest, header and report identity before exposing content',async()=>{const {metadata,bytes,body}=exported(),receipt=healthExport(metadata,'voice');const api=(payload:Uint8Array,sha=metadata.sha256)=>new HealthHistoryApi(connection,hash,async()=>new Response(payload as BodyInit,{headers:{'Content-Type':'application/json','X-Content-SHA256':sha}}));assert.equal((await api(bytes).contents(receipt)).report_id,id);await assert.rejects(api(bytes,'e'.repeat(64)).contents(receipt));await assert.rejects(api(new Uint8Array(bytes.length)).contents(receipt));const forged=new TextEncoder().encode(JSON.stringify({...body,report_id:'f'.repeat(32)})),forgedHash=await hash(forged);await assert.rejects(api(forged,forgedHash).contents({...receipt,bytes:forged.length,sha256:forgedHash}));await assert.rejects(new HealthHistoryApi(connection,hash,async()=>json({},404)).contents(receipt),/过期/);});
test('leaving the account during bootstrap cannot issue a later export mutation',async()=>{let live=true,writes=0;const api=new HealthHistoryApi(connection,hash,async(_input,init)=>{if(init?.method==='POST')writes++;live=false;return json({token:'csrf',identities:[{id:'daily'}]});},()=>live);await assert.rejects(api.create('same-request-123456','voice'),/已切换/);assert.equal(writes,0);});
