"use strict";
(() => {
  let items=[], goals=[], selected=null, editing=null, requestKey=null, signature="", zone=Intl.DateTimeFormat().resolvedOptions().timeZone;
  const states={active:"按约定进行",paused:"已暂停",finished:"这次安排已结束",cancelled:"已结束"};
  const kindNames={note:"笔记",task:"任务",event:"日程"};
  const outcomes={pending:"本轮进行中",silent:"已检查，没有需要打扰你的变化",completed_unverified:"Wearing 已回应",verified:"结果已核对",failed:"本轮遇到问题",stopped:"本轮未继续",closed_by_user:"已处理",skipped:"已跳过"};
  const fmt=(value,tz=zone)=>value?new Intl.DateTimeFormat("zh-CN",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit",timeZone:tz}).format(new Date(value)):"";
  const localValue=value=>{const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
  function when(item){const s=item.schedule;if(s.kind==="life_change")return `${s.changes.record_kinds.map(k=>kindNames[k]).join("、")}有变化时`;if(s.kind==="once")return fmt(s.at,s.timezone);const p=s.cron.split(/\s+/);if(p[2]==="*"&&p[3]==="*"&&/^\d+$/.test(p[0])&&/^\d+$/.test(p[1])){const day=p[4]==="*"?"每天":p[4]==="1-5"?"周一至周五":/^\d$/.test(p[4])?"每周"+["日","一","二","三","四","五","六"][Number(p[4])%7]:null;if(day)return `${day} ${p[1].padStart(2,"0")}:${p[0].padStart(2,"0")}`;}return `自定重复 · ${s.cron}`;}
  function render(){
    const visible=items.filter(x=>x.status!=="cancelled");
    $("schedules-list").innerHTML=visible.length?visible.map(x=>`<button class="schedule-row" data-schedule="${esc(x.id)}"><div><strong>${esc(x.schedule.title)}</strong><small>${esc(when(x))} · ${esc(states[x.status])}${x.next_run?`<br>下次 ${esc(fmt(x.next_run,x.schedule.timezone))}`:""}</small></div><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 5 7 7-7 7"/></svg></button>`).join(""):'<p class="schedule-empty">有件事，想让 Wearing 持续惦记？<br>可以在聊天里交代，也可以在这里安排。</p>';
    if(selected){const latest=items.find(x=>x.id===selected.id);if(latest){selected=latest;renderDetail();}}
  }
  async function load(){const [data,currentGoals]=await Promise.all([api("/api/schedules"),api("/api/goals")]);goals=currentGoals;const sig=JSON.stringify(data.items);items=data.items;if(sig!==signature){signature=sig;render();}$("schedule-service-note").textContent=state.deployment==="cloud"?"关闭网页也会继续；私人服务需保持运行。结果会回到对话里。":"关闭网页也会继续；本机服务需保持运行。结果会回到对话里。";}
  function frequency(){const value=$("schedule-frequency").value;$("schedule-date-label").hidden=value!=="once";$("schedule-date").required=value==="once";$("schedule-time-label").hidden=["once","custom","life_change"].includes(value);$("schedule-time").required=!["once","custom","life_change"].includes(value);$("schedule-week-label").hidden=value!=="weekly";$("schedule-cron-label").hidden=value!=="custom";$("schedule-cron").required=value==="custom";$("schedule-changes").hidden=value!=="life_change";$("schedule-goal-label").hidden=value!=="life_change";$("schedule-run-limit").disabled=value!=="life_change";$("schedule-timezone").hidden=value==="life_change";$("schedule-timezone").textContent=`时间按 ${zone} 安排。`;
  }
  function closeForm(){editing=null;requestKey=null;$("schedule-form").hidden=true;$("new-schedule").hidden=false;$("schedules-list").hidden=!!selected;$("schedule-detail").hidden=!selected;}
  function form(item=null){editing=item;requestKey=window.WearingIds.uuid();$("schedule-form").reset();zone=item?.schedule.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone;$("schedule-title").value=item?.schedule.title||"";$("schedule-instruction").value=item?.schedule.instruction||"";$("schedule-date").value=localValue(item?.schedule.at||Date.now()+3600000);$("schedule-grace").value=String(item?.schedule.grace_minutes||60);
    if(item&&![...$("schedule-grace").options].some(o=>Number(o.value)===item.schedule.grace_minutes))$("schedule-grace").add(new Option(`${item.schedule.grace_minutes} 分钟`,String(item.schedule.grace_minutes),true,true));
    if(item?.schedule.kind==="cron"){const p=item.schedule.cron.split(/\s+/);$("schedule-cron").value=item.schedule.cron;$("schedule-frequency").value="custom";if(p[2]==="*"&&p[3]==="*"&&/^\d+$/.test(p[0])&&/^\d+$/.test(p[1])){const f=p[4]==="*"?"daily":p[4]==="1-5"?"weekdays":/^[0-6]$/.test(p[4])?"weekly":"custom";$("schedule-frequency").value=f;$("schedule-time").value=`${p[1].padStart(2,"0")}:${p[0].padStart(2,"0")}`;if(f==="weekly")$("schedule-week").value=p[4];}}
    if(item?.schedule.kind==="life_change"){
      $("schedule-frequency").value="life_change";
      const changes=item.schedule.changes;
      document.querySelectorAll('[name="schedule-kind"]').forEach(el=>{el.checked=changes.record_kinds.includes(el.value);});
      for(const [id,key,unit] of [["schedule-debounce","debounce_seconds","秒"],["schedule-cooldown","cooldown_minutes","分钟"]]){const el=$(id);if(![...el.options].some(o=>Number(o.value)===changes[key]))el.add(new Option(`${changes[key]} ${unit}`,String(changes[key])));el.value=String(changes[key]);}
      $("schedule-run-limit").value=changes.max_runs_per_day;
    }
    if($("schedule-frequency").value==="once")zone=Intl.DateTimeFormat().resolvedOptions().timeZone;
    $("schedule-goal").replaceChildren(new Option("独立安排", ""),...goals.filter(g=>!["completed","cancelled"].includes(g.status)||g.id===item?.schedule.goal_id).map(g=>new Option(g.objective,g.id)));
    $("schedule-goal").value=item?.schedule.goal_id||"";
    frequency();$("save-schedule").textContent=item?"保存安排":"交给 Wearing";$("schedule-form").hidden=false;$("new-schedule").hidden=true;$("schedules-list").hidden=true;$("schedule-detail").hidden=true;$("schedule-feedback").textContent="";$("schedule-title").focus();
  }
  function renderDetail(){if(!selected)return;const x=selected;$("schedule-detail").innerHTML=`<button type="button" class="text-button" data-schedule-back>返回安排</button><h4>${esc(x.schedule.title)}</h4><p class="schedule-meta">${esc(when(x))} · ${x.schedule.kind==="life_change"?"":`${esc(x.schedule.timezone)} · `}${esc(states[x.status])}</p><p>${esc(x.schedule.instruction)}</p>${x.goal?`<p class="schedule-meta">接着推进：${esc(x.goal.objective)} · 剩余 ${Math.max(0,x.goal.max_steps-x.goal.used_steps)} 轮${["active","waiting"].includes(x.goal.status)?"":" · 目标当前未在推进"}</p>`:""}${x.reason?`<p>${esc(x.reason)}</p>`:""}${x.schedule.kind==="life_change"?`<p class="schedule-meta">连续修改合并处理 · 至少间隔 ${x.schedule.changes.cooldown_minutes} 分钟 · 24 小时内最多 ${x.schedule.changes.max_runs_per_day} 次</p>`:""}${x.next_run?`<p class="schedule-meta">下次 ${esc(fmt(x.next_run,x.schedule.timezone))}</p>`:""}<div class="button-row">${x.status!=="cancelled"?`<button class="secondary" data-schedule-edit>修改安排</button>${["active","paused"].includes(x.status)?`<button class="text-button" data-schedule-action="${x.status==="active"?"pause":"resume"}">${x.status==="active"?"暂停后续":"恢复安排"}</button>`:""}<button class="text-button" data-schedule-action="cancel">结束这项安排</button>`:""}</div><details class="schedule-history"><summary>最近的行动 · ${x.occurrences.length} 次记录</summary><ul>${x.occurrences.map(o=>`<li><time>${esc(fmt(o.due_at,x.schedule.timezone))}</time><p>${esc(outcomes[o.status]||o.status)}</p>${o.status!=="silent"?`<p>${esc(o.reason||o.error||(x.goal?"本轮进展已归入原目标，可在对话中查看。":o.output)||"正在等待回应。")}</p>`:""}</li>`).join("")||'<li><p>按约定行动后，记录会留在这里。</p></li>'}</ul></details>`;}
  async function open(id){$("schedule-feedback").textContent="";await load();selected=items.find(x=>x.id===id);if(!selected)throw new Error("这项安排不在当前身份中。");closeForm();renderDetail();$("schedule-detail").hidden=false;$("schedules-section").scrollIntoView({block:"start",behavior:state.motionPaused?"instant":"smooth"});}
  $("new-schedule").addEventListener("click",()=>form());$("close-schedule-form").addEventListener("click",closeForm);$("schedule-frequency").addEventListener("change",()=>{if($("schedule-frequency").value==="once")zone=Intl.DateTimeFormat().resolvedOptions().timeZone;frequency();});
  $("schedule-form").addEventListener("submit",event=>{event.preventDefault();busy($("save-schedule"),async()=>{const f=$("schedule-frequency").value,[h,m]=$("schedule-time").value.split(":");const schedule={title:$("schedule-title").value.trim(),instruction:$("schedule-instruction").value.trim(),kind:f==="once"?"once":f==="life_change"?"life_change":"cron",timezone:zone,at:f==="once"?new Date($("schedule-date").value).toISOString():null,cron:["once","life_change"].includes(f)?null:f==="custom"?$("schedule-cron").value.trim():`${Number(m)} ${Number(h)} * * ${f==="daily"?"*":f==="weekdays"?"1-5":$("schedule-week").value}`,grace_minutes:Number($("schedule-grace").value),goal_id:f==="life_change"?$("schedule-goal").value||null:null,changes:f==="life_change"?{record_kinds:[...document.querySelectorAll('[name="schedule-kind"]:checked')].map(el=>el.value),debounce_seconds:Number($("schedule-debounce").value),cooldown_minutes:Number($("schedule-cooldown").value),max_runs_per_day:Number($("schedule-run-limit").value)}:null};
    if(f==="life_change"&&!schedule.changes.record_kinds.length)throw new Error("至少选一种要留意的记录。");
    const result=await api(editing?`/api/schedules/${editing.id}`:"/api/schedules",{method:editing?"PATCH":"POST",body:JSON.stringify(editing?{revision:editing.revision,action:"edit",schedule}:{schedule,request_key:requestKey})});selected=null;closeForm();await load();$("schedule-feedback").textContent=result.status==="paused"?"已保存，仍然暂停。恢复后会按新安排执行。":result.goal&&!["active","waiting"].includes(result.goal.status)?"已关联。目标当前未在推进，继续目标后才会留意新变化。":result.schedule.kind==="life_change"?"记下了。从现在开始，有新变化我会留意。":`记下了，下次 ${fmt(result.next_run,result.schedule.timezone)}。`;$("new-schedule").focus();},$("schedule-feedback"));});
  $("schedules-section").addEventListener("click",event=>{const row=event.target.closest("[data-schedule]");if(row){busy(row,()=>open(row.dataset.schedule),$("schedule-feedback"));return;}if(event.target.closest("[data-schedule-back]")){selected=null;closeForm();$("schedule-detail").hidden=true;$("schedules-list").hidden=false;return;}if(event.target.closest("[data-schedule-edit]")){form(selected);return;}const action=event.target.closest("[data-schedule-action]");if(action&&selected)busy(action,async()=>{selected=await api(`/api/schedules/${selected.id}`,{method:"PATCH",body:JSON.stringify({revision:selected.revision,action:action.dataset.scheduleAction})});await load();renderDetail();$("schedule-feedback").textContent=selected.status==="paused"?"后续安排已暂停。已开始的本轮可在对话中停止。":"已更新安排。";},$("schedule-feedback"));});
  document.addEventListener("click",event=>{const button=event.target.closest("[data-open-schedule]");if(button){openPanel("keeps-panel");open(button.dataset.openSchedule).catch(error=>{$("schedule-feedback").textContent=error.message;});}});
  window.WearingSchedules={load,identityChanged(){items=[];goals=[];selected=null;signature="";closeForm();$("schedules-list").replaceChildren();$("schedule-detail").replaceChildren();$("schedule-feedback").textContent="";}};
})();
